name: Build and Upload Binary to Releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码库
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: 安装依赖（shc 编译器）
    - name: Install SHC
      run: sudo apt-get update && sudo apt-get install -y shc

    # Step 3: 编译脚本为二进制文件
    - name: Compile logcatlog.sh
      run: |
        mkdir -p build
        chmod +x ./scripts/logcatlog.sh
        shc -f ./scripts/logcatlog.sh -o ./build/logcatlog

    # Step 4: 创建 Release 并上传文件
    - name: Create or Update Release
      uses: ncipollo/release-action@v1
      with:
        tag: v1.0.0
        name: logcatlog Binary v1.0.0
        body: |
          This release includes the compiled binary for logcatlog.sh.
        draft: false
        prerelease: false
        artifacts: ./build/logcatlog
